---
- name: install tool
  ansible.builtin.include_tasks: "{{ item }}"
  when: install_tools is undefined or (item | basename)[0:-4] in install_tools
  loop: "{{ lookup('fileglob', 'tasks/package/*.yml', wantlist=True) }}"
