---
- name: change permission {{ item }} data directory
  file:
    path: "{{ wwwsqldesigner_dest }}/backend/{{ item }}"
    mode: "0777"
    state: directory
- name: change permission {{ item }} database file
  file:
    path: "{{ wwwsqldesigner_dest }}/backend/{{ item }}/wwwsqldesigner.sqlite"
    mode: "0666"
    state: file
