galaxy_info:
  author: yoshiaki tanaka
  description: setup memcached
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags: []
dependencies: []
