---
- name: Converge
  hosts: all
  gather_facts: true
  become: true
  vars:
    php_version: 7.4
  roles:
    - role: php
  pre_tasks:
    - name: dump vars
      block:
        - name: create dump directory
          file:
            path: dump_vars
            state: directory
          changed_when: false
        - name: dump vars
          blockinfile:
            path: "dump_vars/{{ inventory_hostname }}.yml"
            create: true
            block: "{{ vars | to_json }}"
          changed_when: false
      connection: local
      become: false
