---
- name: install dependency packages
  yum:
    name:
      - python-requests
      - python-babel
      - python-boto3
      - python2-future
      - python-idna
    enablerepo: epel
- name: install lexicon
  pip:
    name: dns-lexicon
    state: latest
  tags: skip_ansible_lint
