---
galaxy_info:
  author: yoshiaki tanaka
  description: setup dehydrated
  license: MIT
  min_ansible_version: 2.5
  platforms:
    - name: EL
      versions:
        - 7

dependencies:
  - repo-epel
