---
- name: create backup data directory
  file:
    path: "{{ backup_dir }}"
    state: directory
    mode: "0755"
- name: create backup scripts directory
  file:
    path: "{{ backup_script_dir }}"
    state: directory
    mode: "0755"
- name: download backup script
  get_url:
    url: "{{ item.url }}"
    dest: "{{ backup_script_dir }}/{{ item.name | default(item.url | basename) }}"
    checksum: "{{ item.checksum | default(omit) }}"
    url_username: "{{ item.auth_basic_user | default(omit) }}"
    url_password: "{{ item.auth_basic_password | default(omit) }}"
    mode: "0755"
  loop: "{{ backup_settings | selectattr('url', 'defined') | list }}"
  loop_control:
    label: "{{ item.name }}"
- name: upload backup script(script file)
  copy:
    src: "{{ item.file }}"
    dest: "{{ backup_script_dir }}/{{ item.script_name | default(item.file | basename) }}"
    mode: "0755"
  loop: "{{ backup_settings | selectattr('file', 'defined') | list }}"
  loop_control:
    label: "{{ item.name }}"
- name: upload backup script(jinja templete file)
  template:
    src: "{{ item.template }}"
    dest: "{{ backup_script_dir }}/{{ item.script_name | default(item.template | basename | regex_replace('.j2$', '')) }}"
    mode: "0755"
  loop: "{{ backup_settings | selectattr('template', 'defined') | list }}"
  loop_control:
    label: "{{ item.name }}"
- name: manage backup settings
  cron:
    name: "{{ item.name }}"
    job: "{{ item.command }}"
    minute: "{{ item.minute | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    user: "{{ item.user | default('root') }}"
    disabled: "{{ item.disabled | default(false) }}"
    state: "{{ tem.state | default(true) | ternary('present', 'absent') }}"
  loop: "{{ backup_settings }}"
  loop_control:
    label: "{{ item.name }}"
