---
dependency:
  name: galaxy
driver:
  name: vagrant
vagrant:
  platforms:
    - name: centos
      box: wate/centos-7
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 512
        cpus: 1
  instances:
    - name: wp-cli
      ansible_groups:
        - molecule
verifier:
  name: serverspec
