---
- name: install dependency packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
- name: add apt signing key
  ansible.builtin.apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present
- name: Add php repository
  ansible.builtin.apt_repository:
    filename: php
    repo: deb https://packages.sury.org/php/ {{ ansible_facts.distribution_release }} main
    state: present
- name: update package cach
  ansible.builtin.apt:
    update_cache: true
