---
- name: install dehydrated
  ansible.builtin.apt:
    name:
      - dehydrated
      - cron
- name: install lexicon
  ansible.builtin.apt:
    name: "{{ dehydrated_lexicon_packages }}"
  when: dehydrated_with_lexicon
- name: create addtitional config file
  ansible.builtin.template:
    src: local.sh.j2
    dest: "{{ dehydrated_config_dir }}/local.sh"
    mode: "0644"
- name: create domain file
  ansible.builtin.template:
    src: domains.txt.j2
    dest: "{{ dehydrated_domains_txt }}"
    mode: "0644"
- name: create hook file
  ansible.builtin.template:
    src: hook.sh.j2
    dest: "{{ dehydrated_config_base_dir }}/hook.sh"
    mode: "0750"
- name: register account key
  ansible.builtin.command:
    cmd: dehydrated --register --accept-terms
    creates: "{{ dehydrated_base_dir }}/accounts"
- name: create auth file directory
  ansible.builtin.file:
    path: /var/www/dehydrated
    state: directory
    mode: "0755"
- name: sign/renew non-existent/changed/expiring certificates
  ansible.builtin.command:
    cmd: dehydrated --cron
  when: dehydrated_auto_execute
- name: register cron job
  ansible.builtin.cron:
    name: Update SSL certificate
    job: "{{ dehydrated_cron.job }}"
    hour: "{{ dehydrated_cron.hour | string }}"
    minute: "{{ dehydrated_cron.minute | string }}"
