---
galaxy_info:
  author: yoshiaki tanaka
  description: install remi repogitory
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
  galaxy_tags: []

dependencies:
  - repo-epel
