---
- name: update load load balancing method module setting
  lineinfile:
    path: /etc/httpd/conf.modules.d/00-proxy.conf
    regexp: "^#?LoadModule lbmethod_{{ item.key }}_module modules/mod_lbmethod_{{ item.key }}.so"
    line: "{{ '' if item.value else '#' }}LoadModule lbmethod_{{ item.key }}_module modules/mod_lbmethod_{{ item.key }}.so"
  notify: restart apache
  loop: "{{ apache_module_lbmethod | dict2items }}"
