---
- name: Set Install version variable
  when: font_plemoljp_version == 'latest'
  block:
    - name: Set Github API request header
      ansible.builtin.set_fact:
        github_api_request_headers:
          Accept: application/vnd.github+json
    - name: Merge Github API Authorization request header
      ansible.builtin.set_fact:
        github_api_request_headers: "{{ github_api_request_headers | combine(merge_reauest_header) }}"
      vars:
        merge_reauest_header:
          Authorization: Bearer {{ lookup('env', 'GITHUB_TOKEN') }}
      when: lookup('env', 'GITHUB_TOKEN') | length > 0
    - name: Get latest release
      ansible.builtin.uri:
        url: https://api.github.com/repos/{{ font_plemoljp_repo }}/releases/latest
        headers: "{{ github_api_request_headers }}"
      register: latest_releases
    - name: Set package version variable
      ansible.builtin.set_fact:
        font_plemoljp_version: "{{ latest_releases.json.tag_name }}"
- name: Set asset file variable
  ansible.builtin.set_fact:
    asset_url: https://github.com/{{ font_plemoljp_repo }}/releases/download/{{ font_plemoljp_version }}/PlemolJP_{{ font_plemoljp_version }}.zip
- name: Create font directory
  ansible.builtin.file:
    path: "{{ font_dir }}/PlemolJP"
    state: directory
    mode: "0755"
- name: Install font file
  ansible.builtin.unarchive:
    src: "{{ asset_url }}"
    dest: "{{ font_dir }}/PlemolJP"
    extra_opts:
      - -j
    remote_src: true
