---
# 7.0 OR 7.1 OR 7.2 OR 7.3 OR 7.4 OR 8.0 OR 8.1
php_version: '7.4'

php_packages:
  - php{{ php_version }}-common
  - php{{ php_version }}-cli
  - php{{ php_version }}-dev
  - php{{ php_version }}-curl
  - php{{ php_version }}-gd
  - php{{ php_version }}-bcmath
  - php{{ php_version }}-mbstring
  - php{{ php_version }}-bz2
  - php{{ php_version }}-gettext
  - php{{ php_version }}-sqlite3
  - php{{ php_version }}-mysqlnd
  - php{{ php_version }}-pdo
  - php{{ php_version }}-opcache
  - php{{ php_version }}-intl
  - php{{ php_version }}-imagick
  - php{{ php_version }}-xml
  - php{{ php_version }}-zip
  - php{{ php_version }}-apcu
  - php{{ php_version }}-fpm
  # - php{{ php_version }}-redis
  # - php{{ php_version }}-memcached
  # - php{{ php_version }}-xdebug

php_cfg: |
  date.timezone = Asia/Tokyo
php_cli_cfg: "{{ php_cfg }}"
php_fpm_cfg: "{{ php_cfg }}"
php_apache_cfg: "{{ php_cfg }}"

php_composer_version: latest-stable
