---
galaxy_info:
  author: yoshiaki tanaka
  description: install Node.js
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7

dependencies:
  - repo-epel
