---
- name: Verify
  hosts: all
  gather_facts: true
  check_mode: true
  tasks:
    - name: test apt signing key
      apt_key:
        url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
        state: present
      register: result
    - name: assert apt signing key
      assert:
        that: result is not changed
    - name: test repository
      apt_repository:
        filename: influxdb
        repo: deb https://deb.nodesource.com/node_16.x {{ ansible_facts.distribution_release }} main
        state: present
      register: result
    - name: assert repository
      assert:
        that: result is not changed
    - name: test package
      apt:
        name: nodejs
      register: result
    - name: assert package
      assert:
        that: result is not changed
