---
apache_packages:
  - httpd
  - mod_ssl

apache_vhosts:
  - name: 00-default
    server_name: www.example.com
    document_root: /var/www/html
    server_alias:
      - example.com
    # directory_index:
    #   - index.html
    #   - index.php
    # options:
    #   - "-Indexes"
    #   - "+FollowSymLinks"
    # allow_override: None
    # require:
    #   - type: ip
    #     value: "192.168.33.0/24"
    # custom_log:
    #   path: logs/access_log
    #   format: combined
    # error_log:
    #   path: logs/error_log
    #   log_level: warn
    # transfer_log:
    #   path: logs/transfer_log
    #   format: %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"'
    # alias:
    #   - from: /phpMyAdmin
    #     to: /usr/share/phpMyAdmin
    #   - from: /phpmyAdmin
    #     to: /usr/share/phpMyAdmin
    # proxy_pass:
    #   - from: /
    #     to: "http://127.0.0.1:8080/"
    # proxy_pass_reverse:
    #   - from: /
    #     to: "http://127.0.0.1:8080/"
    # proxy_pass_match:
    #   - pattern: ^(.*\.php(/.*)?)$
    #     to: unix:/path/to/socket.sock | fcgi://127.0.0.1:9000/path/to/your/documentroot/"
    # ssl:
    #   certificate_file: /path/to/signed_certificate_followed_by_intermediate_certs
    #   certificate_key_file: /path/to/private/key
    #   protocol:
    #     - all
    #     - "-SSLv3"
    #     - "-TLSv1"
    #     - "-TLSv1.1"
    #   cipher_suite:
    #     - ECDHE-ECDSA-AES256-GCM-SHA384
    #     - ECDHE-RSA-AES256-GCM-SHA384
    #     - ECDHE-ECDSA-CHACHA20-POLY1305
    #     - ECDHE-RSA-CHACHA20-POLY1305
    #     - ECDHE-ECDSA-AES128-GCM-SHA256
    #     - ECDHE-RSA-AES128-GCM-SHA256
    #     - ECDHE-ECDSA-AES256-SHA384
    #     - ECDHE-RSA-AES256-SHA384
    #     - ECDHE-ECDSA-AES128-SHA256
    #     - ECDHE-RSA-AES128-SHA256
    #   certificate_chain_file: /path/to/ca_certs_for_client_authentication
    #   honor_cipher_order: yes
    #   compression: no
    #   stapling_responder_timeout: 5
    #   stapling_return_responder_errors: no
    #   stapling_cache: "shmcb:/var/run/ocsp(128000)"
    #   hsts: "max-age=15768000"
    # ip: 127.0.0.1
    # port: 1080
    # extra_param: |
    #   <Location /server-status>
    #     SetHandler server-status
    #     Require ip 127.0.0.1
    #   </Location>

apache_secrity_cfg:
  trace_enable: no
  server_tokens: Prod
  headers:
    "X-Frame-Options": SAMEORIGIN
    "X-Content-Type-Options": nosniff
    "X-XSS-Protection": '"1; mode=block"'

apache_cfg:
  server_admin: root@localhost
  enable_sendfile: yes
  # extra_param: |
  #   ExtendedStatus On

# Apache MPM(Multi Processing Module)
# Setting Value: prefork OR worker OR event
apache_module_mpm: prefork

apache_ssl_cfg:
    protocol:
      - all
      - "-SSLv3"
    cipher_suite:
      - ECDHE-ECDSA-CHACHA20-POLY1305
      - ECDHE-RSA-CHACHA20-POLY1305
      - ECDHE-ECDSA-AES128-GCM-SHA256
      - ECDHE-RSA-AES128-GCM-SHA256
      - ECDHE-ECDSA-AES256-GCM-SHA384
      - ECDHE-RSA-AES256-GCM-SHA384
      - DHE-RSA-AES128-GCM-SHA256
      - DHE-RSA-AES256-GCM-SHA384
      - ECDHE-ECDSA-AES128-SHA256
      - ECDHE-RSA-AES128-SHA256
      - ECDHE-ECDSA-AES128-SHA
      - ECDHE-RSA-AES256-SHA384
      - ECDHE-RSA-AES128-SHA
      - ECDHE-ECDSA-AES256-SHA384
      - ECDHE-ECDSA-AES256-SHA
      - ECDHE-RSA-AES256-SHA
      - DHE-RSA-AES128-SHA256
      - DHE-RSA-AES128-SHA
      - DHE-RSA-AES256-SHA256
      - DHE-RSA-AES256-SHA
      - ECDHE-ECDSA-DES-CBC3-SHA
      - ECDHE-RSA-DES-CBC3-SHA
      - EDH-RSA-DES-CBC3-SHA
      - AES128-GCM-SHA256
      - AES256-GCM-SHA384
      - AES128-SHA256
      - AES256-SHA256
      - AES128-SHA
      - AES256-SHA
      - DES-CBC3-SHA
      - "!DSS"
    honor_cipher_order: yes
    compression: no
    use_stapling: yes
    stapling_responder_timeout: 5
    stapling_return_responder_errors: no
    stapling_cache: "shmcb:/var/run/ocsp(128000)"

apache_module_base:
  buffer: no
  watchdog: no
  heartbeat: no
  heartmonitor: no
  usertrack: no
  dialup: no
  charset_lite: no
  log_debug: no
  ratelimit: no
  reflector: no
  request: no
  sed: no
  speling: no

apache_module_dav:
  dav: yes
  dav_fs: yes
  dav_lock: yes

apache_module_lua: yes

apache_module_lbmethod:
  bybusyness: yes
  byrequests: yes
  bytraffic: yes
  heartbeat: yes

apache_module_proxy:
  ajp: yes
  balancer: yes
  connect: yes
  express: yes
  fcgi: yes
  fdpass: yes
  ftp: yes
  http: yes
  wstunnel: yes
