---
- name: add epel repository
  yum:
    name: epel-release
- name: change repository status
  ini_file:
    path: /etc/yum.repos.d/epel.repo
    section: epel
    option: enabled
    value: "{{ '1' if repo_epel_enabled else '0' }}"
    mode: "0644"
