---
galaxy_info:
  author: yoshiaki tanaka
  description: setup php
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags: []

dependencies:
  - repo-remi
